        <?php if(isset($errors['id'])): ?>
                <p class="message"><?= $errors['id'] ?></p>
            <?php endif; ?>
        <input id="id" type="text" name="id" value="<?= $book["id"] ?>" class="hide"/>
        <p>
            <label for="isbn">ISBN</label>
            <?php if(isset($errors['isbn'])): ?>
                <p class="message"><?= $errors['isbn'] ?></p>
            <?php endif; ?>
            <input id="isbn" type="text" name="isbn" required value="<?= $book['isbn'] ??'' ?>"/>
        </p>
        <p>
            <label for="auteur">Auteur</label>
            <?php if(isset($errors['auteur'])): ?>
                <p class="message"><?= $errors['auteur'] ?></p>
            <?php endif; ?>
            <input id="auteur" type="text" name="auteur" required value="<?= $book['auteur'] ??'' ?>"/>
        </p>
        <p>
            <label for="titre">Titre</label>
            <?php if(isset($errors['titre'])): ?>
                <p class="message"><?= $errors['titre'] ?></p>
            <?php endif; ?>
            <input id="titre" type="text" name="titre" required value="<?= $book['titre'] ??'' ?>"/>
        </p>
        <p>
            <label for="editeur">Editeur</label>
            <?php if(isset($errors['editeur'])): ?>
                <p class="message"><?= $errors['editeur'] ?></p>
            <?php endif; ?>
            <input id="editeur" type="text" name="editeur" required value="<?= $book['editeur'] ??'' ?>"/>
        </p>
        <p>
            <label for="date">Date de parution</label>
            <?php if(isset($errors['date'])): ?>
                <p class="message"><?= $errors['date'] ?></p>
            <?php endif; ?>
            <input id="date" type="date" name="date" required value="<?= $book['date_par'] ??'' ?>"/>
        </p>
        <p>
            <label for="collection">Collection</label>
            <input id="collection" type="text" name="collection" value="<?= $book['collection'] ??'' ?>"/>
        </p>
        <p>
            <label for="genre">Genre</label>
            <?php if(isset($errors['genre'])): ?>
                <p class="message"><?= $errors['genre'] ?></p>
            <?php endif; ?>
            <input id="genre" type="text" name="genre" required value="<?= $book['genre'] ??'' ?>"/>
        </p>
        <p>
            <label for="tome">Tome</label>
            <?php if(isset($errors['tome'])): ?>
                <p class="message"><?= $errors['tome'] ?></p>
            <?php endif; ?>
            <input id="tome" type="number" name="tome" value="<?= $book['tome'] ??'' ?>"/>
        </p>
        <p>
            <label for="nombre">Nombre de pages</label>
            <?php if(isset($errors['nombre'])): ?>
                <p class="message"><?= $errors['nombre'] ?></p>
            <?php endif; ?>
            <input id="nombre" type="number" name="nombre" required value="<?= $book['nbre_pages'] ??'' ?>"/>
        </p>
        <p>
            <label for="format">Format</label>
            <?php if(isset($errors['format'])): ?>
                <p class="message"><?= $errors['format'] ?></p>
            <?php endif; ?>
            <input id="format" type="text" name="format" required value="<?= $book['format'] ??'' ?>"/>
        </p>
        <p>
            <label for="resume">Résumé</label>
            <?php if(isset($errors['resume'])): ?>
                <p class="message"><?= $errors['resume'] ?></p>
            <?php endif; ?>
            <textarea id="resume" name="resume" required><?= $book['resume'] ??'' ?></textarea>
        </p>
        <p>
            <label for="cle">Mots-clés (séparés par un espace)</label>
            <?php if(isset($errors['cle'])): ?>
                <p class="message"><?= $errors['cle'] ?></p>
            <?php endif; ?>
            <textarea id="cle" name="cle" required><?= $book['mot_cles'] ??'' ?></textarea>
        </p>
        <p>
            <label for="cote">Cote</label>
            <?php if(isset($errors['cote'])): ?>
                <p class="message"><?= $errors['cote'] ?></p>
            <?php endif; ?>
            <input id="cote" type="text" name="cote" required value="<?= $book['cote'] ??'' ?>"/>
        </p>
        <p>
            <label for="localisation">Localisation interne</label>
            <?php if(isset($errors['localisation'])): ?>
                <p class="message"><?= $errors['localisation'] ?></p>
            <?php endif; ?>
            <input id="localisation" type="text" name="localisation" required value="<?= $book['localisation_interne'] ??'' ?>"/>
        </p>
        <p>
            <label for="categorie">Catégorie</label>
            <?php if(isset($errors['categorie'])): ?>
                <p class="message"><?= $errors['categorie'] ?></p>
            <?php endif; ?>
            <select name="categorie" id="categorie">
                <option selected><?= $book['categorie'] ??'' ?></option>
                <option value="action">action</option>
                <option value="comédie">comédie</option>
                <option value="cuisine">cuisine</option>
                <option value="documentaire">documentaire</option>
                <option value="fantastique">fantastique</option>
                <option value="historique">historique</option>
                <option value="horreur">horreur</option>
                <option value="poésie">poésie</option>
                <option value="policier">policier</option>
                <option value="romance">romance</option>
                <option value="science-fiction">science-fiction</option>
                <option value="théâtre">théâtre</option>
            </select>
        </p>
        <p>
            <label for="image">Image</label>
            <div><img src="public/assets/images/<?= $book["image"] ?>" alt="<?= $book["titre"] ?>"/></div>
            <input id="image" type="file" name="image" accept=".png, .jpg, .jpeg"/>
        </p>