<input type="text" name="id" value="<?= $user["id"] ?>" class="hide"/>
<input type="text" name="tel" class="infosInput" value="<?= $user["tel"] ?>"/>
<input type="text" name="adresse" class="infosInput" value="<?=$user["adresse"] ?>"/>
<input type="text" name="cp" class="infosInput" value="<?=$user["code_postal"] ?>"/>
<input type="text" name="ville" class="infosInput" value="<?=$user["Ville"] ?>"/>
<input type="email"  name="email" class="infosInput" value="<?= $user["email"] ?>"/>
<button type="submit" class="save"><i class="fas fa-save"></i></button>

        