<div id="menuSearch" class="menuSearch">
    <form method="GET" action="index.php" class="form">
        <div class="position">
            <input type="search" id="researchWords" name="bookList" class="inputSearch" autocomplete="off" placeholder="Rechercher un livre"/><!--autocomplete permet d'enlever les recherches passées qui s'affiche au-dessus de ma liste de recherche-->
            <div id="targetResearch" class="result hide"></div>
        </div>
        <button type="submit" class="validate">Recherche avancée</button>
    </form>
</div>
<h2>Mes Favoris</h2>
<button type="button" class="buttonForm deleteWishList">Vider la wishlist</button>
<div id="targetWishList" class="bookDesc"></div>
