<h2>Infos pratiques</h2>
<div class="info-pratiques">
    <h3>Inscription</h3>
    <p>L'inscription à la bibliothèque est gratuite. L'inscription permet de bénéficier de la totalité des services offerts par la bibliothèque : prêt de documents, animations culturelles, accès à Internet. La création d'un compte lecteur est nécessaire à la finalisation de l'inscription et vous permettra d'avoir accès aux services en ligne suivants : réservation de livres, liste de vos réservations et de vos prêts, liste de favoris.</p>
    <p>En vous inscrivant vous acceptez le réglement intérieur de la bibliothèque.</p>
    <h3>Réglement intérieur</h3>
    <p>Le réglement intérieur est disponible sur le site physique de la bibliothèque.</p>
    <h3>Les réservations</h3>
    <p>En tant qu'inscrit, vous avez la possibilité de résever un livre via le site internet de la bibliothèque. Le document réservé sera mis de côté pendant 15 jours, vous devez donc venir le récupérer durant ce délai. Si votre réservation est précédée d'un prêt, vous pouvez nous contacter avant de vous déplacer afin de vous confirmer si le document a bien été rendu et est donc disponible. Sans aucune nouvelle de votre part, au-delà de 15 jours le livre sera remis à disposition du public. Vous pouvez également supprimer votre réservation en ligne.</p>
    <h3>Les prêts</h3>
    <p>Le prêt est consenti pour une durée de 1 mois. Au-delà de cette durée, vous pouvez venir renouveler 1 fois votre document sur place uniquement (future fonctionnalité en ligne), sous condition que le document emprunté ne soit pas réservé par un autre usager.</p>
</div>

