<div class="mentionsLegales">
    <div>
        <h2>Identité</h2>
        <div class="div-mentions">
            <p>Biliothèque.com</p>
            <p class="site">http://anaellecussac.sites.3wa.io/developpement/Bibliotheque</p>
            <p>Propriétaire: Anaëlle Cussac</p>
            <p>Contact fictif: biblio@gmail.com</p>
            <p>Adresse fictive: X rue de la Marine, 13000 MARSEILLE</p>
        </div>
    </div>
    <div>
        <h2>Hébergeur du site</h2>
        <div class="div-mentions">
            <p>3W Academy</p>
            <p>Adresse: 46-48 rue René Clair 75018 Paris</p>
            <p>Téléphone: 01 75 43 42 42</p>
        </div>
    </div>
</div>
