<h2>Politique de confidentialité de la Bibliothèque</h2>
<div class="privacy">
    <h3>Introduction</h3>
    <p class="site">Dans le cadre de son activité, la bibliothèque est amenée à collecter et à traiter des informations dont certaines sont qualifiées de "données personnelles". La Bibliothèque attache une grande importance au respect de la vie privée, et n’utilise que des donnes de manière responsable et confidentielle et dans une finalité précise. La présente politique vous informe sur les conditions d’utilisation des données à caractère personnel, que la bibliothèque est conduite à collecter et traiter, dans le cadre de ses activités et du site http://anaellecussac.sites.3wa.io/developpement/Bibliotheque.</p>
    
    <h3>Données personnelles</h3>
    <p class="site">Sur le site web http://anaellecussac.sites.3wa.io/developpement/Bibliotheque, différents types de données sont susceptibles d’être recueillies :</p>
    
    <h4>Gestion des inscrits à la Bibliothèque</h4>
    <p>Les données collectées lors de votre inscription aux services de la Bibliothèque ou sur notre site Internet font l’objet de traitements dont la finalité est la création de votre adhésion et la gestion de nos interactions. La durée de conservation des données correspond à la durée de votre adhésion et ne peut excéder 1 an après votre radiation.</p>
     
    <h4>Gestion des collections</h4>
    <p>Les données collectées lors de la réservation ou l’emprunt de documents font l’objet de traitements dont la finalité est le suivi des documents. La durée de conservation des données, notamment de l’historique des documents empruntés, correspond à la durée de l'action.</p>
     
    <h4>Participation à des évènements</h4>
    <p>Les données collectées lors de votre participation à des ateliers font l’objet d’un traitement dont la finalité est la gestion de votre participation à des évènements. La durée de conservation des données est de 5 ans après votre participation.</p>
    
    <h4>Gestion des demandes de contact</h4>
    <p>Les données collectées lors de l’utilisation de notre page de contact font l’objet d’un traitement dont la finalité est la gestion de votre demande. La durée de conservation correspond à la durée de l'action.</p>
     
    <h3>L’application des principes de protection</h3>
     
    <h4>Types de données</h4>
    <p>Les types de données personnelles qui sont collectées pour la gestion de nos services peuvent être :</p>
    <ul>
        <li>Nom, prénom, date de naissance, adresse, email, téléphone, photo, numéro étudiant/lecteur, …</li>
        <li>Historique de vos emprunts,</li>
        <li>Participation à nos évènements (nom de notre atelier, date, nom, prénom)</li>
        <li>Données de connexion</li>
    </ul>
    
    <h4>Destinataires des données</h4>
    <p>Les destinataires des données personnelles sont les services internes de la bibliothèque.</p>
    
    <h3>Droits sur vos données personnelles</h3>
    
    <h4>Droit d’accès</h4>
    <p>Vous pouvez nous demander la confirmation que des données à caractère personnel vous concernant sont ou non traitées par nos soins. Vous avez par ailleurs un droit d’accès aux données personnelles que nous détenons vous concernant. Vous pouvez formuler une demande de copie de ces informations, par écrit et accompagnée d’une copie d’un titre d’identité signé et à jour.</p>
    
    <h4>Droit de rectification</h4>
    <p>Vous disposez d’un droit de rectification de données inexactes ou incomplètes. Il vous suffit pour cela de nous faire parvenir par écrit une déclaration complémentaire.</p>
    
    <h4>Droit à l’effacement</h4>
    <p>Vous avez le droit de demander l'effacement de vos données à caractère personnel, dans le cas où vous êtes en règle auprès de la bibliothèque (restitution de tous les documents, aucun emprunt).</p>
    
    <h4>Droit d’opposition</h4>
    <p>Vous pouvez vous opposer, pour des raisons tenant à votre situation particulière, à un traitement de données à caractère personnel vous concernant dès lors qu’il a pour base légale notre intérêt légitime.</p>
    
    <h3>Contact à la protection des données</h3>
    <p>bibliothèque - biblio@gmail.com</p>
</div>